print("-" * 100)
print("WELCOME TO DELHI DAYS!")
print("-" * 100)
print("-" * 100)
price1 = int(input("Price of Item 1: "))
price2 = int(input("Price of Item 2: "))
price3 = int(input("Price of Item 3: "))
print("-" * 100)
print("DISCOUNT DETAILS:")
disc1 = int(input("Provide discount (in percentage) for the 1st Saver Combo: "))
disc2 = int(input("Provide discount (in percentage) for the 2nd Saver Combo: "))
disc3 = int(input("Provide discount (in percentage) for the 3rd Saver Combo: "))
print("-" * 100)
num = int(input("Provide 10 digit number: "))
print("The resulting catalogue is:")
print("-" * 100)
print("-" * 100)
print("Delhi Days")
print("R-Block, Model Town 3")
print("Delhi: 110099")
print("-" * 100)
print("-" * 100)
print("Item      Price Pack")
print("|          |         ")
print("Item1      " + str(price1))
print("Item2      " + str(price2))
print("Item3      " + str(price3))
print("ComboPack1 " + str(int((price1 + price2) * (100 - disc1) / 100)))
print("ComboPack2 " + str(int((price1 + price3) * (100 - disc2) / 100)))
print("ComboPack3 " + str(int((price3 + price2) * (100 - disc3) / 100)))
print("SuperSaver " + str(int((price3 + price2) * 72 / 100)))
print("-" * 100)
print()
print("For home delivery call: ", num)
print()
